// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requestMessage.proto

package com.zy.common.message.generate;

public final class RequestMessageProtoBuf {
  private RequestMessageProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GameRequestMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GameRequestMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string cmd = 1;</code>
     * @return The cmd.
     */
    java.lang.String getCmd();
    /**
     * <code>string cmd = 1;</code>
     * @return The bytes for cmd.
     */
    com.google.protobuf.ByteString
        getCmdBytes();

    /**
     * <code>int64 userUid = 2;</code>
     * @return The userUid.
     */
    long getUserUid();

    /**
     * <code>.C2G_LoginParms C2G_LoginParms = 3;</code>
     * @return Whether the c2GLoginParms field is set.
     */
    boolean hasC2GLoginParms();
    /**
     * <code>.C2G_LoginParms C2G_LoginParms = 3;</code>
     * @return The c2GLoginParms.
     */
    com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms getC2GLoginParms();
    /**
     * <code>.C2G_LoginParms C2G_LoginParms = 3;</code>
     */
    com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParmsOrBuilder getC2GLoginParmsOrBuilder();

    public com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg.DataBodyCase getDataBodyCase();
  }
  /**
   * Protobuf type {@code GameRequestMsg}
   */
  public static final class GameRequestMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GameRequestMsg)
      GameRequestMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GameRequestMsg.newBuilder() to construct.
    private GameRequestMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GameRequestMsg() {
      cmd_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GameRequestMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GameRequestMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              cmd_ = s;
              break;
            }
            case 16: {

              userUid_ = input.readInt64();
              break;
            }
            case 26: {
              com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms.Builder subBuilder = null;
              if (dataBodyCase_ == 3) {
                subBuilder = ((com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zy.common.message.generate.RequestMessageProtoBuf.internal_static_GameRequestMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zy.common.message.generate.RequestMessageProtoBuf.internal_static_GameRequestMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg.class, com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg.Builder.class);
    }

    private int dataBodyCase_ = 0;
    private java.lang.Object dataBody_;
    public enum DataBodyCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      C2G_LOGINPARMS(3),
      DATABODY_NOT_SET(0);
      private final int value;
      private DataBodyCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 3: return C2G_LOGINPARMS;
          case 0: return DATABODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public static final int CMD_FIELD_NUMBER = 1;
    private volatile java.lang.Object cmd_;
    /**
     * <code>string cmd = 1;</code>
     * @return The cmd.
     */
    @java.lang.Override
    public java.lang.String getCmd() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cmd_ = s;
        return s;
      }
    }
    /**
     * <code>string cmd = 1;</code>
     * @return The bytes for cmd.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCmdBytes() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERUID_FIELD_NUMBER = 2;
    private long userUid_;
    /**
     * <code>int64 userUid = 2;</code>
     * @return The userUid.
     */
    @java.lang.Override
    public long getUserUid() {
      return userUid_;
    }

    public static final int C2G_LOGINPARMS_FIELD_NUMBER = 3;
    /**
     * <code>.C2G_LoginParms C2G_LoginParms = 3;</code>
     * @return Whether the c2GLoginParms field is set.
     */
    @java.lang.Override
    public boolean hasC2GLoginParms() {
      return dataBodyCase_ == 3;
    }
    /**
     * <code>.C2G_LoginParms C2G_LoginParms = 3;</code>
     * @return The c2GLoginParms.
     */
    @java.lang.Override
    public com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms getC2GLoginParms() {
      if (dataBodyCase_ == 3) {
         return (com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms) dataBody_;
      }
      return com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms.getDefaultInstance();
    }
    /**
     * <code>.C2G_LoginParms C2G_LoginParms = 3;</code>
     */
    @java.lang.Override
    public com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParmsOrBuilder getC2GLoginParmsOrBuilder() {
      if (dataBodyCase_ == 3) {
         return (com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms) dataBody_;
      }
      return com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCmdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cmd_);
      }
      if (userUid_ != 0L) {
        output.writeInt64(2, userUid_);
      }
      if (dataBodyCase_ == 3) {
        output.writeMessage(3, (com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms) dataBody_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCmdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cmd_);
      }
      if (userUid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, userUid_);
      }
      if (dataBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms) dataBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg)) {
        return super.equals(obj);
      }
      com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg other = (com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg) obj;

      if (!getCmd()
          .equals(other.getCmd())) return false;
      if (getUserUid()
          != other.getUserUid()) return false;
      if (!getDataBodyCase().equals(other.getDataBodyCase())) return false;
      switch (dataBodyCase_) {
        case 3:
          if (!getC2GLoginParms()
              .equals(other.getC2GLoginParms())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd().hashCode();
      hash = (37 * hash) + USERUID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserUid());
      switch (dataBodyCase_) {
        case 3:
          hash = (37 * hash) + C2G_LOGINPARMS_FIELD_NUMBER;
          hash = (53 * hash) + getC2GLoginParms().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GameRequestMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GameRequestMsg)
        com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zy.common.message.generate.RequestMessageProtoBuf.internal_static_GameRequestMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zy.common.message.generate.RequestMessageProtoBuf.internal_static_GameRequestMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg.class, com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg.Builder.class);
      }

      // Construct using com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cmd_ = "";

        userUid_ = 0L;

        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zy.common.message.generate.RequestMessageProtoBuf.internal_static_GameRequestMsg_descriptor;
      }

      @java.lang.Override
      public com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg getDefaultInstanceForType() {
        return com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg build() {
        com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg buildPartial() {
        com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg result = new com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg(this);
        result.cmd_ = cmd_;
        result.userUid_ = userUid_;
        if (dataBodyCase_ == 3) {
          if (c2GLoginParmsBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = c2GLoginParmsBuilder_.build();
          }
        }
        result.dataBodyCase_ = dataBodyCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg) {
          return mergeFrom((com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg other) {
        if (other == com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg.getDefaultInstance()) return this;
        if (!other.getCmd().isEmpty()) {
          cmd_ = other.cmd_;
          onChanged();
        }
        if (other.getUserUid() != 0L) {
          setUserUid(other.getUserUid());
        }
        switch (other.getDataBodyCase()) {
          case C2G_LOGINPARMS: {
            mergeC2GLoginParms(other.getC2GLoginParms());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataBodyCase_ = 0;
      private java.lang.Object dataBody_;
      public DataBodyCase
          getDataBodyCase() {
        return DataBodyCase.forNumber(
            dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }


      private java.lang.Object cmd_ = "";
      /**
       * <code>string cmd = 1;</code>
       * @return The cmd.
       */
      public java.lang.String getCmd() {
        java.lang.Object ref = cmd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cmd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cmd = 1;</code>
       * @return The bytes for cmd.
       */
      public com.google.protobuf.ByteString
          getCmdBytes() {
        java.lang.Object ref = cmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cmd = 1;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cmd = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        
        cmd_ = getDefaultInstance().getCmd();
        onChanged();
        return this;
      }
      /**
       * <code>string cmd = 1;</code>
       * @param value The bytes for cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cmd_ = value;
        onChanged();
        return this;
      }

      private long userUid_ ;
      /**
       * <code>int64 userUid = 2;</code>
       * @return The userUid.
       */
      @java.lang.Override
      public long getUserUid() {
        return userUid_;
      }
      /**
       * <code>int64 userUid = 2;</code>
       * @param value The userUid to set.
       * @return This builder for chaining.
       */
      public Builder setUserUid(long value) {
        
        userUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userUid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserUid() {
        
        userUid_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms, com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms.Builder, com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParmsOrBuilder> c2GLoginParmsBuilder_;
      /**
       * <code>.C2G_LoginParms C2G_LoginParms = 3;</code>
       * @return Whether the c2GLoginParms field is set.
       */
      @java.lang.Override
      public boolean hasC2GLoginParms() {
        return dataBodyCase_ == 3;
      }
      /**
       * <code>.C2G_LoginParms C2G_LoginParms = 3;</code>
       * @return The c2GLoginParms.
       */
      @java.lang.Override
      public com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms getC2GLoginParms() {
        if (c2GLoginParmsBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            return (com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms) dataBody_;
          }
          return com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 3) {
            return c2GLoginParmsBuilder_.getMessage();
          }
          return com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms.getDefaultInstance();
        }
      }
      /**
       * <code>.C2G_LoginParms C2G_LoginParms = 3;</code>
       */
      public Builder setC2GLoginParms(com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms value) {
        if (c2GLoginParmsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          c2GLoginParmsBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.C2G_LoginParms C2G_LoginParms = 3;</code>
       */
      public Builder setC2GLoginParms(
          com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms.Builder builderForValue) {
        if (c2GLoginParmsBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          c2GLoginParmsBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.C2G_LoginParms C2G_LoginParms = 3;</code>
       */
      public Builder mergeC2GLoginParms(com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms value) {
        if (c2GLoginParmsBuilder_ == null) {
          if (dataBodyCase_ == 3 &&
              dataBody_ != com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms.getDefaultInstance()) {
            dataBody_ = com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms.newBuilder((com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 3) {
            c2GLoginParmsBuilder_.mergeFrom(value);
          }
          c2GLoginParmsBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.C2G_LoginParms C2G_LoginParms = 3;</code>
       */
      public Builder clearC2GLoginParms() {
        if (c2GLoginParmsBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          c2GLoginParmsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.C2G_LoginParms C2G_LoginParms = 3;</code>
       */
      public com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms.Builder getC2GLoginParmsBuilder() {
        return getC2GLoginParmsFieldBuilder().getBuilder();
      }
      /**
       * <code>.C2G_LoginParms C2G_LoginParms = 3;</code>
       */
      @java.lang.Override
      public com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParmsOrBuilder getC2GLoginParmsOrBuilder() {
        if ((dataBodyCase_ == 3) && (c2GLoginParmsBuilder_ != null)) {
          return c2GLoginParmsBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 3) {
            return (com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms) dataBody_;
          }
          return com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms.getDefaultInstance();
        }
      }
      /**
       * <code>.C2G_LoginParms C2G_LoginParms = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms, com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms.Builder, com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParmsOrBuilder> 
          getC2GLoginParmsFieldBuilder() {
        if (c2GLoginParmsBuilder_ == null) {
          if (!(dataBodyCase_ == 3)) {
            dataBody_ = com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms.getDefaultInstance();
          }
          c2GLoginParmsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms, com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms.Builder, com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParmsOrBuilder>(
                  (com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 3;
        onChanged();;
        return c2GLoginParmsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GameRequestMsg)
    }

    // @@protoc_insertion_point(class_scope:GameRequestMsg)
    private static final com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg();
    }

    public static com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GameRequestMsg>
        PARSER = new com.google.protobuf.AbstractParser<GameRequestMsg>() {
      @java.lang.Override
      public GameRequestMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameRequestMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GameRequestMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GameRequestMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zy.common.message.generate.RequestMessageProtoBuf.GameRequestMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface C2G_LoginParmsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:C2G_LoginParms)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string account = 1;</code>
     * @return The account.
     */
    java.lang.String getAccount();
    /**
     * <code>string account = 1;</code>
     * @return The bytes for account.
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code C2G_LoginParms}
   */
  public static final class C2G_LoginParms extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:C2G_LoginParms)
      C2G_LoginParmsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use C2G_LoginParms.newBuilder() to construct.
    private C2G_LoginParms(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C2G_LoginParms() {
      account_ = "";
      password_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new C2G_LoginParms();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private C2G_LoginParms(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              account_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zy.common.message.generate.RequestMessageProtoBuf.internal_static_C2G_LoginParms_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zy.common.message.generate.RequestMessageProtoBuf.internal_static_C2G_LoginParms_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms.class, com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms.Builder.class);
    }

    public static final int ACCOUNT_FIELD_NUMBER = 1;
    private volatile java.lang.Object account_;
    /**
     * <code>string account = 1;</code>
     * @return The account.
     */
    @java.lang.Override
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        account_ = s;
        return s;
      }
    }
    /**
     * <code>string account = 1;</code>
     * @return The bytes for account.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private volatile java.lang.Object password_;
    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    @java.lang.Override
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAccountBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, account_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAccountBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, account_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms)) {
        return super.equals(obj);
      }
      com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms other = (com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms) obj;

      if (!getAccount()
          .equals(other.getAccount())) return false;
      if (!getPassword()
          .equals(other.getPassword())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAccount().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code C2G_LoginParms}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:C2G_LoginParms)
        com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParmsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zy.common.message.generate.RequestMessageProtoBuf.internal_static_C2G_LoginParms_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zy.common.message.generate.RequestMessageProtoBuf.internal_static_C2G_LoginParms_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms.class, com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms.Builder.class);
      }

      // Construct using com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        account_ = "";

        password_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zy.common.message.generate.RequestMessageProtoBuf.internal_static_C2G_LoginParms_descriptor;
      }

      @java.lang.Override
      public com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms getDefaultInstanceForType() {
        return com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms.getDefaultInstance();
      }

      @java.lang.Override
      public com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms build() {
        com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms buildPartial() {
        com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms result = new com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms(this);
        result.account_ = account_;
        result.password_ = password_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms) {
          return mergeFrom((com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms other) {
        if (other == com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms.getDefaultInstance()) return this;
        if (!other.getAccount().isEmpty()) {
          account_ = other.account_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object account_ = "";
      /**
       * <code>string account = 1;</code>
       * @return The account.
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string account = 1;</code>
       * @return The bytes for account.
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string account = 1;</code>
       * @param value The account to set.
       * @return This builder for chaining.
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        account_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string account = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccount() {
        
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      /**
       * <code>string account = 1;</code>
       * @param value The bytes for account to set.
       * @return This builder for chaining.
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        account_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 2;</code>
       * @return The password.
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       * @return The bytes for password.
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       * @param value The password to set.
       * @return This builder for chaining.
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @param value The bytes for password to set.
       * @return This builder for chaining.
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:C2G_LoginParms)
    }

    // @@protoc_insertion_point(class_scope:C2G_LoginParms)
    private static final com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms();
    }

    public static com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<C2G_LoginParms>
        PARSER = new com.google.protobuf.AbstractParser<C2G_LoginParms>() {
      @java.lang.Override
      public C2G_LoginParms parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2G_LoginParms(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C2G_LoginParms> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C2G_LoginParms> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zy.common.message.generate.RequestMessageProtoBuf.C2G_LoginParms getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GameRequestMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GameRequestMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_C2G_LoginParms_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_C2G_LoginParms_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024requestMessage.proto\"e\n\016GameRequestMsg" +
      "\022\013\n\003cmd\030\001 \001(\t\022\017\n\007userUid\030\002 \001(\003\022)\n\016C2G_Lo" +
      "ginParms\030\003 \001(\0132\017.C2G_LoginParmsH\000B\n\n\010dat" +
      "aBody\"3\n\016C2G_LoginParms\022\017\n\007account\030\001 \001(\t" +
      "\022\020\n\010password\030\002 \001(\tB8\n\036com.zy.common.mess" +
      "age.generateB\026RequestMessageProtoBufb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GameRequestMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GameRequestMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GameRequestMsg_descriptor,
        new java.lang.String[] { "Cmd", "UserUid", "C2GLoginParms", "DataBody", });
    internal_static_C2G_LoginParms_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_C2G_LoginParms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_C2G_LoginParms_descriptor,
        new java.lang.String[] { "Account", "Password", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
