// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: responeMessage.proto

package com.zy.common.message.generate;

public final class ResponeMessageProtoBuf {
  private ResponeMessageProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GameResponeMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GameResponeMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 error = 1;</code>
     * @return The error.
     */
    int getError();

    /**
     * <code>string cmd = 2;</code>
     * @return The cmd.
     */
    java.lang.String getCmd();
    /**
     * <code>string cmd = 2;</code>
     * @return The bytes for cmd.
     */
    com.google.protobuf.ByteString
        getCmdBytes();

    /**
     * <code>.G2C_LoginParms G2C_LoginParms = 3;</code>
     * @return Whether the g2CLoginParms field is set.
     */
    boolean hasG2CLoginParms();
    /**
     * <code>.G2C_LoginParms G2C_LoginParms = 3;</code>
     * @return The g2CLoginParms.
     */
    com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms getG2CLoginParms();
    /**
     * <code>.G2C_LoginParms G2C_LoginParms = 3;</code>
     */
    com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParmsOrBuilder getG2CLoginParmsOrBuilder();

    public com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg.DataBodyCase getDataBodyCase();
  }
  /**
   * Protobuf type {@code GameResponeMsg}
   */
  public static final class GameResponeMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GameResponeMsg)
      GameResponeMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GameResponeMsg.newBuilder() to construct.
    private GameResponeMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GameResponeMsg() {
      cmd_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GameResponeMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GameResponeMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              error_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              cmd_ = s;
              break;
            }
            case 26: {
              com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms.Builder subBuilder = null;
              if (dataBodyCase_ == 3) {
                subBuilder = ((com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zy.common.message.generate.ResponeMessageProtoBuf.internal_static_GameResponeMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zy.common.message.generate.ResponeMessageProtoBuf.internal_static_GameResponeMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg.class, com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg.Builder.class);
    }

    private int dataBodyCase_ = 0;
    private java.lang.Object dataBody_;
    public enum DataBodyCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      G2C_LOGINPARMS(3),
      DATABODY_NOT_SET(0);
      private final int value;
      private DataBodyCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 3: return G2C_LOGINPARMS;
          case 0: return DATABODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public static final int ERROR_FIELD_NUMBER = 1;
    private int error_;
    /**
     * <code>int32 error = 1;</code>
     * @return The error.
     */
    @java.lang.Override
    public int getError() {
      return error_;
    }

    public static final int CMD_FIELD_NUMBER = 2;
    private volatile java.lang.Object cmd_;
    /**
     * <code>string cmd = 2;</code>
     * @return The cmd.
     */
    @java.lang.Override
    public java.lang.String getCmd() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cmd_ = s;
        return s;
      }
    }
    /**
     * <code>string cmd = 2;</code>
     * @return The bytes for cmd.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCmdBytes() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int G2C_LOGINPARMS_FIELD_NUMBER = 3;
    /**
     * <code>.G2C_LoginParms G2C_LoginParms = 3;</code>
     * @return Whether the g2CLoginParms field is set.
     */
    @java.lang.Override
    public boolean hasG2CLoginParms() {
      return dataBodyCase_ == 3;
    }
    /**
     * <code>.G2C_LoginParms G2C_LoginParms = 3;</code>
     * @return The g2CLoginParms.
     */
    @java.lang.Override
    public com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms getG2CLoginParms() {
      if (dataBodyCase_ == 3) {
         return (com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms) dataBody_;
      }
      return com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms.getDefaultInstance();
    }
    /**
     * <code>.G2C_LoginParms G2C_LoginParms = 3;</code>
     */
    @java.lang.Override
    public com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParmsOrBuilder getG2CLoginParmsOrBuilder() {
      if (dataBodyCase_ == 3) {
         return (com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms) dataBody_;
      }
      return com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (error_ != 0) {
        output.writeInt32(1, error_);
      }
      if (!getCmdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cmd_);
      }
      if (dataBodyCase_ == 3) {
        output.writeMessage(3, (com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms) dataBody_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (error_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, error_);
      }
      if (!getCmdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cmd_);
      }
      if (dataBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms) dataBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg)) {
        return super.equals(obj);
      }
      com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg other = (com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg) obj;

      if (getError()
          != other.getError()) return false;
      if (!getCmd()
          .equals(other.getCmd())) return false;
      if (!getDataBodyCase().equals(other.getDataBodyCase())) return false;
      switch (dataBodyCase_) {
        case 3:
          if (!getG2CLoginParms()
              .equals(other.getG2CLoginParms())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd().hashCode();
      switch (dataBodyCase_) {
        case 3:
          hash = (37 * hash) + G2C_LOGINPARMS_FIELD_NUMBER;
          hash = (53 * hash) + getG2CLoginParms().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GameResponeMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GameResponeMsg)
        com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zy.common.message.generate.ResponeMessageProtoBuf.internal_static_GameResponeMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zy.common.message.generate.ResponeMessageProtoBuf.internal_static_GameResponeMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg.class, com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg.Builder.class);
      }

      // Construct using com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        error_ = 0;

        cmd_ = "";

        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zy.common.message.generate.ResponeMessageProtoBuf.internal_static_GameResponeMsg_descriptor;
      }

      @java.lang.Override
      public com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg getDefaultInstanceForType() {
        return com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg build() {
        com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg buildPartial() {
        com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg result = new com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg(this);
        result.error_ = error_;
        result.cmd_ = cmd_;
        if (dataBodyCase_ == 3) {
          if (g2CLoginParmsBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = g2CLoginParmsBuilder_.build();
          }
        }
        result.dataBodyCase_ = dataBodyCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg) {
          return mergeFrom((com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg other) {
        if (other == com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg.getDefaultInstance()) return this;
        if (other.getError() != 0) {
          setError(other.getError());
        }
        if (!other.getCmd().isEmpty()) {
          cmd_ = other.cmd_;
          onChanged();
        }
        switch (other.getDataBodyCase()) {
          case G2C_LOGINPARMS: {
            mergeG2CLoginParms(other.getG2CLoginParms());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataBodyCase_ = 0;
      private java.lang.Object dataBody_;
      public DataBodyCase
          getDataBodyCase() {
        return DataBodyCase.forNumber(
            dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }


      private int error_ ;
      /**
       * <code>int32 error = 1;</code>
       * @return The error.
       */
      @java.lang.Override
      public int getError() {
        return error_;
      }
      /**
       * <code>int32 error = 1;</code>
       * @param value The error to set.
       * @return This builder for chaining.
       */
      public Builder setError(int value) {
        
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 error = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearError() {
        
        error_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object cmd_ = "";
      /**
       * <code>string cmd = 2;</code>
       * @return The cmd.
       */
      public java.lang.String getCmd() {
        java.lang.Object ref = cmd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cmd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cmd = 2;</code>
       * @return The bytes for cmd.
       */
      public com.google.protobuf.ByteString
          getCmdBytes() {
        java.lang.Object ref = cmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cmd = 2;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cmd = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        
        cmd_ = getDefaultInstance().getCmd();
        onChanged();
        return this;
      }
      /**
       * <code>string cmd = 2;</code>
       * @param value The bytes for cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cmd_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms, com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms.Builder, com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParmsOrBuilder> g2CLoginParmsBuilder_;
      /**
       * <code>.G2C_LoginParms G2C_LoginParms = 3;</code>
       * @return Whether the g2CLoginParms field is set.
       */
      @java.lang.Override
      public boolean hasG2CLoginParms() {
        return dataBodyCase_ == 3;
      }
      /**
       * <code>.G2C_LoginParms G2C_LoginParms = 3;</code>
       * @return The g2CLoginParms.
       */
      @java.lang.Override
      public com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms getG2CLoginParms() {
        if (g2CLoginParmsBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            return (com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms) dataBody_;
          }
          return com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 3) {
            return g2CLoginParmsBuilder_.getMessage();
          }
          return com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms.getDefaultInstance();
        }
      }
      /**
       * <code>.G2C_LoginParms G2C_LoginParms = 3;</code>
       */
      public Builder setG2CLoginParms(com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms value) {
        if (g2CLoginParmsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          g2CLoginParmsBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.G2C_LoginParms G2C_LoginParms = 3;</code>
       */
      public Builder setG2CLoginParms(
          com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms.Builder builderForValue) {
        if (g2CLoginParmsBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          g2CLoginParmsBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.G2C_LoginParms G2C_LoginParms = 3;</code>
       */
      public Builder mergeG2CLoginParms(com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms value) {
        if (g2CLoginParmsBuilder_ == null) {
          if (dataBodyCase_ == 3 &&
              dataBody_ != com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms.getDefaultInstance()) {
            dataBody_ = com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms.newBuilder((com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 3) {
            g2CLoginParmsBuilder_.mergeFrom(value);
          }
          g2CLoginParmsBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.G2C_LoginParms G2C_LoginParms = 3;</code>
       */
      public Builder clearG2CLoginParms() {
        if (g2CLoginParmsBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          g2CLoginParmsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.G2C_LoginParms G2C_LoginParms = 3;</code>
       */
      public com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms.Builder getG2CLoginParmsBuilder() {
        return getG2CLoginParmsFieldBuilder().getBuilder();
      }
      /**
       * <code>.G2C_LoginParms G2C_LoginParms = 3;</code>
       */
      @java.lang.Override
      public com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParmsOrBuilder getG2CLoginParmsOrBuilder() {
        if ((dataBodyCase_ == 3) && (g2CLoginParmsBuilder_ != null)) {
          return g2CLoginParmsBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 3) {
            return (com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms) dataBody_;
          }
          return com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms.getDefaultInstance();
        }
      }
      /**
       * <code>.G2C_LoginParms G2C_LoginParms = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms, com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms.Builder, com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParmsOrBuilder> 
          getG2CLoginParmsFieldBuilder() {
        if (g2CLoginParmsBuilder_ == null) {
          if (!(dataBodyCase_ == 3)) {
            dataBody_ = com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms.getDefaultInstance();
          }
          g2CLoginParmsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms, com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms.Builder, com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParmsOrBuilder>(
                  (com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 3;
        onChanged();;
        return g2CLoginParmsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GameResponeMsg)
    }

    // @@protoc_insertion_point(class_scope:GameResponeMsg)
    private static final com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg();
    }

    public static com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GameResponeMsg>
        PARSER = new com.google.protobuf.AbstractParser<GameResponeMsg>() {
      @java.lang.Override
      public GameResponeMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameResponeMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GameResponeMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GameResponeMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zy.common.message.generate.ResponeMessageProtoBuf.GameResponeMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface G2C_LoginParmsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:G2C_LoginParms)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();
  }
  /**
   * Protobuf type {@code G2C_LoginParms}
   */
  public static final class G2C_LoginParms extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:G2C_LoginParms)
      G2C_LoginParmsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use G2C_LoginParms.newBuilder() to construct.
    private G2C_LoginParms(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private G2C_LoginParms() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new G2C_LoginParms();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private G2C_LoginParms(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zy.common.message.generate.ResponeMessageProtoBuf.internal_static_G2C_LoginParms_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zy.common.message.generate.ResponeMessageProtoBuf.internal_static_G2C_LoginParms_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms.class, com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms)) {
        return super.equals(obj);
      }
      com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms other = (com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms) obj;

      if (getId()
          != other.getId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code G2C_LoginParms}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:G2C_LoginParms)
        com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParmsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zy.common.message.generate.ResponeMessageProtoBuf.internal_static_G2C_LoginParms_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zy.common.message.generate.ResponeMessageProtoBuf.internal_static_G2C_LoginParms_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms.class, com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms.Builder.class);
      }

      // Construct using com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zy.common.message.generate.ResponeMessageProtoBuf.internal_static_G2C_LoginParms_descriptor;
      }

      @java.lang.Override
      public com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms getDefaultInstanceForType() {
        return com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms.getDefaultInstance();
      }

      @java.lang.Override
      public com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms build() {
        com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms buildPartial() {
        com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms result = new com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms) {
          return mergeFrom((com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms other) {
        if (other == com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:G2C_LoginParms)
    }

    // @@protoc_insertion_point(class_scope:G2C_LoginParms)
    private static final com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms();
    }

    public static com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<G2C_LoginParms>
        PARSER = new com.google.protobuf.AbstractParser<G2C_LoginParms>() {
      @java.lang.Override
      public G2C_LoginParms parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new G2C_LoginParms(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<G2C_LoginParms> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<G2C_LoginParms> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zy.common.message.generate.ResponeMessageProtoBuf.G2C_LoginParms getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GameResponeMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GameResponeMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_G2C_LoginParms_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_G2C_LoginParms_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024responeMessage.proto\"c\n\016GameResponeMsg" +
      "\022\r\n\005error\030\001 \001(\005\022\013\n\003cmd\030\002 \001(\t\022)\n\016G2C_Logi" +
      "nParms\030\003 \001(\0132\017.G2C_LoginParmsH\000B\n\n\010dataB" +
      "ody\"\034\n\016G2C_LoginParms\022\n\n\002id\030\001 \001(\005B8\n\036com" +
      ".zy.common.message.generateB\026ResponeMess" +
      "ageProtoBufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GameResponeMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GameResponeMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GameResponeMsg_descriptor,
        new java.lang.String[] { "Error", "Cmd", "G2CLoginParms", "DataBody", });
    internal_static_G2C_LoginParms_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_G2C_LoginParms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_G2C_LoginParms_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
